name: "Build and Release"

on:
  push:
    tags:
    - 'v*'

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  release:
    name: 'Release'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Publish for Windows'
      run: dotnet publish -r win-x64 -c Release -o ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\win -p:AssemblyName=ocel-cli

    - name: 'Publish for Linux'
      run: dotnet publish -r linux-x64 -c Release -o ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\linux -p:AssemblyName=ocel-cli

    - name: 'Publish for OSX'
      run: dotnet publish -r osx-x64 -c Release -o ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\osx -p:AssemblyName=ocel-cli

    - name: 'Create release'
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ steps.version.outputs.version-without-v }}
        tag_name: ${{ github.ref }}
        files: |
          ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\win\*.exe
          ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\linux\*
          ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\osx\*